export const categories = [
  { name: "Clothing", color: "#7A9A01" },
  { name: "Electronics", color: "#5B8A51" },
  { name: "Furniture", color: "#457893" },
  { name: "Toys & Games", color: "#375E97" },
  { name: "Books & Media", color: "#B8AFCA" },
  { name: "Sports Equipment", color: "#883C7F" },
  { name: "Tools & Hardware", color: "#AD446E" },
  { name: "Decoration", color: "#D05158" },
  { name: "Pet Supplies", color: "#F07D42" },
  { name: "Toiletries", color: "#FFA94C" },
  { name: "Art & Craft Supplies", color: "#FFD000" },
  { name: "Garden & Outdoor", color: "#F7E738" },
  { name: "Medical Supplies", color: "#B1D85C" },
  { name: "Baby & Childcare", color: "#74C69D" },
  { name: "Musical Instruments", color: "#5AB8C2" },
  { name: "Office Supplies", color: "#6186A0" },
  { name: "Appliances", color: "#706993" },
  { name: "Miscellaneous Items", color: "#8B5E74" },
];
